<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>GalaxyCommand.GodotClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GalaxyCommand.Simulation/GalaxyCommand.Simulation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../content/built-in/**/*">
      <Link>BuiltInContent/%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
